name:                toy-haskell
version:             0.1.0.0
github:              "githubuser/toy-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/toy-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec == 9.2.0
- filepath == 1.4.2.1
- text == 1.2.5.0
- parser-combinators == 1.2.1
- containers == 0.6.5.1
- mtl == 2.2.2
- llvm-hs-pretty == 0.9.0.0
- llvm-hs-pure == 9.0.0

library:
  source-dirs: src

executables:
  toy-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-haskell

tests:
  toy-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - toy-haskell
    - hspec

default-extensions:
- OverloadedStrings
- TypeApplications
- StrictData
